---
ignore:
  - CVE-2011-1497
  - CVE-2011-2931
  - CVE-2011-4319
  - CVE-2012-1099
  - CVE-2012-2660
  - CVE-2012-2661
  - CVE-2012-2694
  - CVE-2012-2695
  - CVE-2012-3424
  - CVE-2012-3463
  - CVE-2012-3464
  - CVE-2012-3465
  - CVE-2012-6496
  - CVE-2013-0155
  - CVE-2013-0156
  - CVE-2013-0276
  - CVE-2013-0277
  - CVE-2013-1854
  - CVE-2013-1855
  - CVE-2013-1857
  - CVE-2013-4491
  - CVE-2013-6414
  - CVE-2013-6415
  - CVE-2013-6416
  - CVE-2013-6417
  - CVE-2014-0080
  - CVE-2014-0081
  - CVE-2014-0082
  - CVE-2014-0130
  - CVE-2014-3482
  - CVE-2014-3483
  - CVE-2014-3514
  - CVE-2014-7818
  - CVE-2014-7829
  - CVE-2015-1840
  - CVE-2015-3224
  - CVE-2015-3226
  - CVE-2015-3227
  - CVE-2015-7576
  - CVE-2015-7577
  - CVE-2015-7578
  - CVE-2015-7579
  - CVE-2015-7580
  - CVE-2015-7581
  - CVE-2016-0751
  - CVE-2016-0752
  - CVE-2016-0753
  - CVE-2016-2097
  - CVE-2016-2098
  - CVE-2016-6316
  - CVE-2016-6317
  - CVE-2018-16476
  - CVE-2018-16477
  - CVE-2018-3760
  - CVE-2019-5420
  - CVE-2020-8162
  - CVE-2020-8164
  - CVE-2020-8166
  - CVE-2020-8167
  - CVE-2021-22880
  - CVE-2021-22902
  - CVE-2021-22903
  - CVE-2021-22904
  - CVE-2022-21831
  - CVE-2022-22577
  - CVE-2022-23633
  - CVE-2022-31163
  - CVE-2022-3704
  - CVE-2023-22792
  - CVE-2023-22794
  - CVE-2023-22795
  - CVE-2023-22797
  - CVE-2023-22799
  - CVE-2023-23913
  - CVE-2023-28120
  - CVE-2023-38037
  - CVE-2024-26142
  - CVE-2024-26143
  - CVE-2024-26144
  - CVE-2024-28103
  - CVE-2024-32464
  - CVE-2024-34341
  - CVE-2024-41128
  - CVE-2024-47887
  - CVE-2024-47888
  - CVE-2024-53847
  - CVE-2024-54133
