---
ignore:
  - CVE-2012-1099
  - CVE-2012-2695
  - CVE-2012-3464
  - CVE-2012-3465
  - CVE-2012-6496
  - CVE-2013-0155
  - CVE-2013-0156
  - CVE-2013-0276
  - CVE-2013-0277
  - CVE-2013-1854
  - CVE-2013-1855
  - CVE-2013-1857
  - CVE-2014-0081
  - CVE-2014-0130
  - CVE-2014-3482
  - CVE-2014-7818
  - CVE-2015-3227
  - CVE-2015-7579
  - CVE-2016-0751
  - CVE-2016-0753
  - CVE-2016-2097
  - CVE-2016-2098
  - CVE-2016-6316
  - CVE-2019-16782
  - CVE-2019-5418
  - CVE-2019-5419
  - CVE-2020-15169
  - CVE-2020-5267
  - CVE-2020-8163
  - CVE-2020-8165
  - CVE-2020-8166
  - CVE-2020-8167
  - CVE-2021-22885
  - CVE-2021-22902
  - CVE-2021-22903
  - CVE-2021-22904
  - CVE-2022-21831
  - CVE-2022-23633
  - CVE-2022-31163
  - CVE-2023-22794
  - CVE-2023-22797
  # - CVE-2023-23913 # (PLEASE CHECK: Unfixed when using the rails-ujs npm package. Fixed for the bundled `rails-ujs` package for version >= 5.2.8.17. See https://makandracards.com/railslts/541192-installation-instructions-rails-ujs-jquery-ujs.)
  - CVE-2024-26142
  - CVE-2024-26143
  - CVE-2024-26144
  - CVE-2024-28103
  - CVE-2024-32464
  - CVE-2024-34341
  - CVE-2024-47888
  - CVE-2024-53847
